### ISSUE TITLE
Raider does not check if shred exists

### ISSUE THREAD

**Issue by ADBeveridge** [ADBeveridge/raider#1]
When Raider starts it should check if shred (part of the GNU Coreutils) exists. Raider is only meant for Linux, which always has the Coreutils installed, but maybe some dont.

**Comment by sonnyp** [comment]
It's up to the packager to make sure Coreutils is listed as a dependency. I wouldn't worry about this.

**Comment by ADBeveridge** [comment]
Ok, thanks for the info @sonnyp.
