### ISSUE TITLE
Provide instruction to build raider from cmd in terminal

### ISSUE THREAD

**Issue by denisgolius** [ADBeveridge/raider#101]
Could you add "How to" instructions to README.md file which I can use to build [raider](https://github.com/ADBeveridge/raider) from scratch and don't use flatpack/etc on my live-cd/usb ?

**Comment by ADBeveridge** [comment]
Yes, I'll will. For now the instructions are:
```
meson setup builddir
cd builddir
ninja
sudo meson install
```
The setup command may fail a few times because of missing dependencies. Just install them as they go...I'll collect the package list when I edit the README.md

**Comment by stefanhusmann** [comment]
Is there a file missing? 
```
  /usr/bin/glib-compile-resources ../src/raider.gresource.xml --sourcedir src --sourcedir ../src --c-name raider --internal --generate --target src/raider-resources.c --dependency-file src/raider-resources.c.d
../src/raider.gresource.xml: Failed to locate ?raider-window.ui? in any source directory.
[2/11] Generating src/raider-resources_h with a custom command
FAILED: src/raider-resources.h 
/usr/bin/glib-compile-resources ../src/raider.gresource.xml --sourcedir src --sourcedir ../src --c-name raider --internal --generate --target src/raider-resources.h
../src/raider.gresource.xml: Failed to locate ?raider-window.ui? in any source directory.
ninja: build stopped: subcommand failed.
```

**Comment by ADBeveridge** [comment]
At a first look it seems that Blueprint did not build the files, or the filename could be wrong, i'll get back to you when i'm on an internet connection where ipv6 works.

**Comment by JamesL813** [comment]
The AUR version didn't build for me and this is probably why, I got the same message. :thinking:

**Comment by ADBeveridge** [comment]
Do you get any errors about blueprint?

**Comment by JamesL813** [comment]
Here's the output after trying again

```
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /home/james/.cache/paru/clone/raider-file-shredder/src/build
ninja: Entering directory `/home/james/.cache/paru/clone/raider-file-shredder/src/build'
[17/29] Generating src/blueprints with a custom command
usage: blueprint-compiler [-h] [--version] command ...

positional arguments:
  command
    compile      Compile blueprint files
    batch-compile
                 Compile many blueprint files at once
    port         Interactive porting tool
    lsp          Run the language server (for internal use by IDEs)
    help         Show this message

optional arguments:
  -h, --help     show this help message and exit
  --version      show program's version number and exit
[18/29] Generating src/raider-resources_c with a custom command
FAILED: src/raider-resources.c 
/usr/bin/glib-compile-resources ../raider-1.3.1/src/raider.gresource.xml --sourcedir src --sourcedir ../raider-1.3.1/src --c-name raider --internal --generate --target src/raider-resources.c --dependency-file src/raider-resources.c.d
../raider-1.3.1/src/raider.gresource.xml: Failed to locate “raider-window.ui” in any source directory.
[19/29] Generating src/raider-resources_h with a custom command
FAILED: src/raider-resources.h 
/usr/bin/glib-compile-resources ../raider-1.3.1/src/raider.gresource.xml --sourcedir src --sourcedir ../raider-1.3.1/src --c-name raider --internal --generate --target src/raider-resources.h
../raider-1.3.1/src/raider.gresource.xml: Failed to locate “raider-window.ui” in any source directory.
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'raider-file-shredder-1.3.1-1': 
error: packages failed to build: raider-file-shredder-1.3.1-1
```

**Comment by ADBeveridge** [comment]
So the issue is that blueprint is being given the wrong arguments. I'll get back to you by Monday on how to fix it.

**Comment by ADBeveridge** [comment]
So, run `git pull` or redownload the zip file from this repo (you should use devel branch, but unfortunately i am dealing with a race issue with the progress updates), and remove the `blueprint` folder in the subprojects directory if it is there. Don't delete the .wrap file, that is essential. Then run the commands i gave above.

**Comment by Spice-Weasel** [comment]
Hi, cool project! I'd like to document the build process on my system (Ubuntu 22.04). I've forked develop and after installing the following dependencies, I can run `meson setup builddir`.

libgtk4-dev, libawaita-1-dev, gettext, appstream-util.

When running ninja, however - I get the following error.

```
$ ninja
[3/15] Generating src/blueprints with a custom command
FAILED: src 
/home/ingram/repos/raider/builddir/subprojects/blueprint-compiler/blueprint-compiler batch-compile src/. ../src ../src/raider-window.blp ../src/raider-file-row.blp ../src/raider-progress-info-popover.blp ../src/raider-shortcuts.blp
error: Namespace Adw does not contain a type called ToolbarView
at ../src/raider-window.blp line 12 column 7:
  12 |  Adw.ToolbarView {
     |      ^
hint: Did you check your spelling?
hint: Are your dependencies up to date?

[4/15] Generating data/com.github.ADBeveridge.Raider.metainfo.xml with a custom command
ninja: build stopped: subcommand failed.

```

I think this might be related to [140](https://github.com/gdm-settings/gdm-settings/issues/140)

**Comment by ADBeveridge** [comment]
The specific issue here is that Raider's devel branch is targeted for GNOME 45, which introduced a lot of changes for easier dynamic view implementation. GNOME 44 didn't have this ToolbarView. Basically you don't have the beta version of Libadwaita (the GNOME helper library for GTK). I don't recommend installing the beta. 

There is a fix, however...make the Meson build system (which builds the Raider project) download and compile GTK itself if the system gtk and libadwaita libraries don't meet the minimum version requirements.  

I'll add this to the build configuration for Raider. It may take some time, as I'm caught between work and school, but if I find time to weasel (pun unintended 🤣 ) some work in, I will.

**Comment by Spice-Weasel** [comment]
I don't mind weaseling away at it if you're busy. I'm new open source development and essentially searched for an interesting C project in the explorer, if you're open to collaboration - I'd be interested in adding this feature.

**Comment by ADBeveridge** [comment]
That would be appreciated, thanks so much. Here is a roadmap for this to be fixed:

- Update the version requirements for GTK and Libadwaita. 
    - Raider uses Libadwaita 1.4 at a minimum. 
    - Raider uses GTK 4.12 at a minimum.
    - This is what you'll change: https://github.com/ADBeveridge/raider/blob/develop/meson.build#L8.L9
- Add fallback to correct version of gtk (4.12) if the system has not been upgraded.
    - https://mesonbuild.com/Subprojects.html#toggling-between-system-libraries-and-embedded-sources

Feel free to ask me any questions. Open a draft pr as soon as you can, so I can take a look. 

Thanks again 🫠

**Comment by ADBeveridge** [comment]
This is now documented in the BUILD.md file.
