### ISSUE TITLE
Automatic shredding of folder files

### ISSUE THREAD

**Issue by AlexValue** [ADBeveridge/raider#110]
I'd like to suggest a new feature:

Adding folders to the regular shredding list.

That is, the user selects folders and the cleaning interval (1 hour, 3 hours, 1 day, 1 week, 1 month). Files in this folder are automatically shredded according to a schedule.

**Comment by ADBeveridge** [comment]
That would be interesting. But I don't think I would go so far as to rewrite the whole app for DBus so it can run in the background for a scheduled shred. How about I add the feature to shred folders, and then in Files you can open a folder with File Shredder?

**Comment by AlexValue** [comment]
Sounds great. This would be a useful feature.

**Comment by longomes** [comment]
> How about I add the feature to shred folders

Please! This would be more than welcome!

**Comment by ADBeveridge** [comment]
I'm working on this right now. It should be done soon, like within the end of this week.

**Comment by ADBeveridge** [comment]
I ran into some computer troubles, and it will be some time before I can setup my environment again. But this is on my current todo list.

**Comment by ADBeveridge** [comment]
Completed! Will be released tomorrow. Please let me know if there are any bugs with folder shredding through a new issue 😼
