### ISSUE TITLE
"Some files did not exist" message

### ISSUE THREAD

**Issue by longomes** [ADBeveridge/raider#130]
Hi,

When you drag files/a file into the window of the app it shows the message "Some files did not exist" and doesn't run the task.

Best regards!

**Comment by ADBeveridge** [comment]
Install flatseal, select File Shredder in the app sidebar,  and under the Filesystem section enable All User Files.

**Comment by ADBeveridge** [comment]
Otherwise update your system to the latest version of GNOME, since the new file portal in gnome 45 doesn't need explicit file permission to all user files. Which is why I removed the permission. If you cant update, just grant the permission again in flatseal.

**Comment by longomes** [comment]
> Install flatseal, select File Shredder in the app sidebar, and under the Filesystem section enable All User Files.

Thank you so much! That alone has helped me.
