### ISSUE TITLE
Drop app icon transparency

### ISSUE THREAD

**Issue by bertob** [ADBeveridge/raider#133]
The transparency in the app icon makes it look glitchy on some backgrounds because you can't really see the strips inside, e.g. on white:

![image](https://github.com/ADBeveridge/raider/assets/1908896/1e004e61-b34a-4ef9-8fa2-629a46af1a0a)

I'd drop the transparency and just use colors similar to how it looks with the black background in the example above.

**Comment by ADBeveridge** [comment]
![image](https://github.com/ADBeveridge/raider/assets/91360682/a30d5a44-a8c6-46b8-8fee-aedb3ff0dfc5)
how does this look? best i could do with my limited inkscape skills :)

fyi, i actually didn't make this icon, jannuary(noelle) made it.

**Comment by bertob** [comment]
Hard to tell without actually trying it on a few different backgrounds, but it does look like an improvement. Let's go with this and iterate if necessary :)

**Comment by ADBeveridge** [comment]
Okay

**Comment by ADBeveridge** [comment]
![image](https://github.com/ADBeveridge/raider/assets/91360682/4aa4286c-9896-4239-8956-be11670ff042)
