### ISSUE TITLE
App listing quality

### ISSUE THREAD

**Issue by bertob** [ADBeveridge/raider#134]
The app listing is pretty high quality, but there are a few minor issues:

- Needs brand colors
- The first screenshot should not show an empty state, but how the app looks in action (i.e. with some files opened). That's because the first screenshot is the one used on featured banners on Flathub.
- Not mandatory, but would be nice to fix the icon transparency issue #133 

Flathub quality guidelines: https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines

**Comment by ADBeveridge** [comment]
Once I finish my work with adding shredding folders, I'll work on these. Shouldn't be more than a couple weeks.

**Comment by ADBeveridge** [comment]
Might be 10 more days, since I am out of town for the next week. But will do it when I get back.

**Comment by ADBeveridge** [comment]
Fixed the screenshot issue, waiting on your reply on the icon issue before i work on branding colors.

**Comment by ADBeveridge** [comment]
Added branding colors. First (and now only) screenshot shows Raider in action.
