### ISSUE TITLE
Slovenian translaton

### ISSUE THREAD

**Issue by MatejKovacic** [ADBeveridge/raider#138]
Hi, a couple of weeks ago I contributed Slovenian translation. Today I got new version from Flathub (3.0.0), but when I run it, it is in English language.

Did something went wrong or I am doing something wrong? I have Ubuntu 23.10.

**Comment by ADBeveridge** [comment]
I"ll have to test it, but I think what's going on is the POT file got updated (I changed some strings) but the Slovenian file didn't. So you'll have to update the slovenian translation with the POT file again.

**Comment by MatejKovacic** [comment]
OK, how to do that?

I am attaching zipped .po file...

[sl_SI.zip](https://github.com/ADBeveridge/raider/files/15224612/sl_SI.zip)

**Comment by ADBeveridge** [comment]
The instructions are in the readme file in the po/ directory. You can also view it here (scroll down to the bottom): https://github.com/ADBeveridge/raider/tree/develop/po.

You'll want to run the xgettext program (full command in readme), this command updates the POT file. Then open your sl_SL.po file in POEdit, and under the Translation menu, click Update from POT File. Then retranslate, commit, open pr, the usual thing. 

I'll have to update the instructions, they are not as clear as i remembered.

**Comment by ADBeveridge** [comment]
Updated the README in the po directory
