### ISSUE TITLE
File Shredder doesn't appear in "Open With..." dialog on GNOME

### ISSUE THREAD

**Issue by jroyvde** [ADBeveridge/raider#154]
Currently (at least for me), File Shredder 3.0.1 does not show up in the "Open With..." file dialog on GNOME, using GNOME Files. It would be a really good quality of life and efficiency feature to have this working.

I am using the Flatpak version of File Shredder 3.0.1 on Fedora 41.

**Comment by ADBeveridge** [comment]
Yeah this is because I haven't started using the GNOME 47 SDK. Will fix next week after finals.

**Comment by ADBeveridge** [comment]
Completed! Should be pushing to Flatpak in a few hours.
