### ISSUE TITLE
Icon Design Compliance With GNOME HIG

### ISSUE THREAD

**Issue by ADBeveridge** [ADBeveridge/raider#2]
Redesign the icon so it is compliant with the [GNOME Icon HIG](https://developer.gnome.org/hig/guidelines/app-icons.html?highlight=icon).

**Comment by ADBeveridge** [comment]
What would be the best icon meaning for File Shredder? A box with paper going in representing a real-life paper shredder. Or a piece of slightly bent paper with one half of it like a kaleidoscope, using a monochromatic green, and the other half pure green?

**Comment by jannuary** [comment]
An iteration on the former:
![image](https://user-images.githubusercontent.com/27908024/149612321-3d1c6837-1dae-40f9-a244-43789353d405.png)

**Comment by ADBeveridge** [comment]
The pure white ring around the top seems to stand out too much. I would like to change it to a lighter gray, like the perspective part at the bottom of the icon. Can you make it available to me? Also, would it look better if I colored the icon? Like the strips into blue. Blue seems to be a common color.

**Comment by jannuary** [comment]
Not sure what you mean by 'coloring', plus I think it's fine to have it more toned down for a utility like this. I will iterate and send a PR later though.

**Comment by ADBeveridge** [comment]
When you put in the PR, also replace the previous artwork creator with your name. It's this [line](https://github.com/ADBeveridge/raider/blob/main/src/raider.c#L122). Creatype made the previous icon, although not for me, I just found it on https://www.flaticon.com.

**Comment by ADBeveridge** [comment]
Flathub complains that the symbolic version is not valid, and GitHub refuses to load it. Could you open a new PR that fixes that?
