### ISSUE TITLE
File Shredder installed from Flathub invokes generic Wayland icon under KDE Plasma 5.24.5 (both window switcher and task manager side)

### ISSUE THREAD

**Issue by lomapur** [ADBeveridge/raider#27]
**Description**

File Shredder's icon (version 0.1.0 installed from Flathub) is not being picked up by neither window switcher nor task manager when using under KDE Plasma 5.24.5 in Wayland session (generic Wayland icon is being used instead).

**Steps to reproduce**
1. Install File Shredder in version 0.1.0 from Flathub on system with KDE Plasma 5.24.5.
2. Make sure Plasma is running in Wayland mode (on Fedora 36 KDE it can be choosen in SDDM display manager).
3. Run File Shredder from either Krunner, Konsole or application launcher.
4. Look at the panel, also press Alt+Tab to show window switcher

**Expected results**
File Shredder's own icon should be shown in both window switcher and on the panel in task manager.

**Actual results**
Generic Wayland icon is shown in both window switcher and on the panel in task manager.

**Screenshots**

![image](https://user-images.githubusercontent.com/3956272/170106041-b4cd681f-8d0e-4e62-901e-7bda767b90e5.png)

**Additional information**

*System information:*
Operating System: Fedora Linux 36
KDE Plasma Version: 5.24.5
KDE Frameworks Version: 5.93.0
Qt Version: 5.15.3
Kernel Version: 5.17.8-300.fc36.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i5-2520M CPU @ 2.50GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 3000

I came across this post by KDE's contributor, Nico, which may help:

https://nicolasfella.de/posts/fixing-wayland-taskbar-icons/

Thank you for your attention!

**Comment by ADBeveridge** [comment]
Can you install a GNOME app like Workbench or Sound Recorder (tell me which one) and see if it has the icon showing or not? If it does I'll see where it differs from mine and see if it can be fixed. Unfortunately, my computer does not support Wayland (It is a revived iMac).

**Comment by ADBeveridge** [comment]
I updated File Shredder. Does it still have that issue?

**Comment by lomapur** [comment]
Hello Alan,

(sorry for late response, life got in the way).

Issue has been fixed, thank you very much!
