### ISSUE TITLE
[Question] How I can add new translation?

### ISSUE THREAD

**Issue by daudix** [ADBeveridge/raider#31]
There is no template.pot, where I can get .po file to translate?

**Comment by ADBeveridge** [comment]
So, right now I'm porting my application to GTK4, and things change a lot very soon, so when I release my beta version of the ported GTK4 app, it will have a `.pot` file. I'll email (on your listed email) or comment (I think it goes to the email also)  you when it's done. Thanks!

**Comment by daudix** [comment]
Thank you!

**Comment by ADBeveridge** [comment]
All done! (For now :)) The pot file is in the po directory. After I get all the translations in, I'll release it as v1.0.0 after some testing (please do some, if you like).

**Comment by ADBeveridge** [comment]
Before releasing to flathub I will implement the polkit stuff for thumb drives (in the split button in the headerbar, but go ahead anyway, will be some time before I understand it.
