### ISSUE TITLE
Update Translations

### ISSUE THREAD

**Issue by ADBeveridge** [ADBeveridge/raider#32]
@oscfdezdz, @albanobattistella, and @eson57, Raider's been ported to GTK4, and the translations need  to be updated. This time, generated a POT file, so this time around should be easier, but please contact me if there is any issues. Thanks! :)

**Comment by ADBeveridge** [comment]
And also the help has changed a little.

**Comment by daudix** [comment]
@ADBeveridge I need some help with translating "Help" page, how can I generate a new .po for it?

**Comment by ADBeveridge** [comment]
I think this is it: https://wiki.gnome.org/TranslationProject/LocalisationGuide#Testing_a_translation_of_software.

**Comment by daudix** [comment]
Thank you!

**Comment by ADBeveridge** [comment]
That above link is wrong (its for testing translations, not creating), this is it: http://projectmallard.org/pipermail/mallard-list/2017-February/000247.html

**Comment by ADBeveridge** [comment]
I'm not sure you have to do that .MO merging stuff though

**Comment by daudix** [comment]
Will try to understand it, hopefully soon ;)

**Comment by daudix** [comment]
Generated .po right now, will make PR soon

**Comment by daudix** [comment]
I have noticed that there is no translation for "Remove Method" in .pot

![Снимок экрана от 2022-07-18 17-54-25](https://user-images.githubusercontent.com/77155297/179539753-d3ebc5eb-5849-425a-a36e-33dd1261c159.png)

**Comment by ADBeveridge** [comment]
It wasn't marked...just updated it, should work now. And updated the POT

**Comment by daudix-UFO** [comment]
> It wasn't marked...just updated it, should work now. And updated the POT

I think that I finished this translation, Sorry for all those "Typo fix" PR's...

**Comment by daudix** [comment]
Another thing i noticed that is not translatable "override file source" when checked show "none selected", I can't translate this
![изображение](https://user-images.githubusercontent.com/77155297/180295192-63e050de-0fb6-4232-9418-eccd7b28982c.png)

**Comment by ADBeveridge** [comment]
Oh, I forgot to add the GSettings file to the POTFILES (that word is bound to the UI in the schema file). It has it now.

**Comment by daudix** [comment]
Thank you!
