### ISSUE TITLE
raider fails to shred files passed via command line

### ISSUE THREAD

**Issue by caribo** [ADBeveridge/raider#53]
raider v1.2.1
manjaro gnome 42.4
Installed from AUR [http://aur.archlinux.org/packages/raider-file-shredder](http://aur.archlinux.org/packages/raider-file-shredder)

when starting raider using the command line and passing filenames, the files are show in the raider UI, but shredding fails.

![image](https://user-images.githubusercontent.com/664999/184474980-7836f28e-883e-40d9-bc50-a9b62c18be9a.png)

```
$ raider /tmp/xyzzy
(raider:20766): GLib-GIO-CRITICAL **: 08:57:44.826: g_file_get_path: assertion 'G_IS_FILE (file)' failed
(raider:20766): GLib-GIO-CRITICAL **: 08:57:44.829: g_file_get_path: assertion 'G_IS_FILE (file)' failed
No shred output found.
(raider:20766): GLib-GObject-CRITICAL **: 08:57:49.773: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

```
or alternatively with a core dump .

```
$ raider /tmp/xyzzy
zsh: segmentation fault (core dumped)  raider /tmp/xyzzy

```

**Comment by ADBeveridge** [comment]
Okay, it's been fixed on the develop branch. The new release will come later though.Thank you!
