### ISSUE TITLE
Notification blocks shred button.

### ISSUE THREAD

**Issue by ghost** [ADBeveridge/raider#57]
After clicking the "Shred All" button the notifications appears one after another for each file shredded and blocks the shred button so the user must click X over and over on all of the notifications or simply wait it out before being able to shred any more files.

**Comment by ghost** [comment]
I guess this might be a duplicate of #55

**Comment by ADBeveridge** [comment]
Not really - the other issue didn't mention this problem (shredding more files after one batch). But the solution is the same: I'll add an option to show notifications or not, and the option to show only one notification at the end of all shredding. Thanks for the input!

**Comment by ADBeveridge** [comment]
This is taking a while, see #60 why.

**Comment by ADBeveridge** [comment]
Okay, there is only one notification, at the end of a successful shredding sesson.
