### ISSUE TITLE
Shred Button Not Red With All Themes

### ISSUE THREAD

**Issue by ADBeveridge** [ADBeveridge/raider#6]
Make sure that the shredding button is always red for all themes. Using the `.destructive-action` class.

**Comment by ADBeveridge** [comment]
How do I use the `.destructive-action` class in my project? Do I list in the Glade box that deals with CSS classes?

**Comment by jannuary** [comment]
```
<style>
  <class name="destructive-action/>
</style>
```
on your widget in the .ui file.

**Comment by ADBeveridge** [comment]
Thanks!
