### ISSUE TITLE
Remove Methods may need some descriptions

### ISSUE THREAD

**Issue by ghost** [ADBeveridge/raider#62]
Hi, 

It's under Advanced Setting and we may ignore but could you add a bit description about removing methods?
I have no idea why I have to select Wipesync instead of Wipe or Unlink.

We may change string someting like this:

- WipeSync, Default, Very secure but slow. 
- Wipe, Less secure but fast. 
- Unlink, Not secure.

![resim](https://user-images.githubusercontent.com/6218679/185584285-4e3f205d-cab6-42be-a22e-8ffdf8c54826.png)

I found the descriptions on this man page: https://man7.org/linux/man-pages/man1/shred.1.html

**Comment by ADBeveridge** [comment]
My initial thought was to put the explanation in the Help file, which is available via the popover menu. But i do not know how many users click on Help though.... Perhaps I could put a few words in parentheses. Lemme see.

**Comment by ADBeveridge** [comment]
Okay, so adding those descriptors results in ellipses, and I want to avoid that. So I added "See help for information." to the end of the subtitle. If a user is inquisitive enough, they'll check the help.
