### ISSUE TITLE
RaiderShredBackend error messages

### ISSUE THREAD

**Issue by caribo** [ADBeveridge/raider#65]
v [e8168f6](https://github.com/ADBeveridge/raider/commit/e8168f6e6c64ba6bdc1862abd1b8faa3d662760e)

Command line error messages issued when testing shredding large number of files. In practice this is more prevalent the greater number of files being shredded and does not seem to happen if shredding smaller numbers < 200.

$ for i in {0001..1000}
do
dd if=/dev/zero of=xyzzy$i count=1024 bs=1024
done

$ raider xyzzy*

(raider:44317): GLib-GObject-WARNING **: 11:42:02.318: invalid uninstantiatable type '(null)' in cast to 'RaiderShredBackend'

(raider:44317): GLib-GObject-WARNING **: 11:42:02.318: invalid uninstantiatable type '(null)' in cast to 'RaiderShredBackend'

(raider:44317): GLib-GObject-WARNING **: 11:42:02.318: invalid uninstantiatable type '(null)' in cast to 'RaiderShredBackend'

(raider:44317): GLib-GObject-WARNING **: 11:42:02.318: invalid unclassed pointer in cast to 'RaiderShredBackend'

(raider:44317): GLib-GObject-WARNING **: 11:42:02.318: invalid uninstantiatable type '<invalid>' in cast to 'RaiderShredBackend'

(raider:44317): GLib-GObject-WARNING **: 11:42:02.318: invalid uninstantiatable type '(null)' in cast to 'RaiderShredBackend'

**Comment by ADBeveridge** [comment]
Is this a flatpak? Because when I run it as a flatpak I get this error:
``` 
** (raider:2): ERROR **: 10:20:14.485: Process launching failed: Too many open files
```

**Comment by ADBeveridge** [comment]
Also, are you getting a bunch of `Before`s?
And did all the files disappear (if the remove option was on)

**Comment by caribo** [comment]
I am building from source on Manjaro / Gnome 42.2

I'm not exactly sure what you mean by "Befores" ; all the messages output are listed in the first post and I can confirm that the files were removed as expected,

**Comment by ADBeveridge** [comment]
`I'm not exactly sure what you mean by "Befores"`: don't worry, just a message i have had. This will probably be fixed by limiting the number of files a user can load, see why I have to do this: https://github.com/ADBeveridge/raider/issues/67. It seems that is error is due to the system, as this only appears when there are lots of instances of the RaiderShredBackend object. So perhaps the system is losing references to those last instances.

**Comment by ADBeveridge** [comment]
Thanks so much for testing Raider, it really is helpful. 😄
