### ISSUE TITLE
Fedora package 

### ISSUE THREAD

**Issue by 0xMRTT** [ADBeveridge/raider#68]
I've created a copr for raider

https://copr.fedorainfracloud.org/coprs/0xmrtt/raider

Run

```
dnf copr enable 0xmrtt/raider 
dnf in raider 
```

**Comment by ADBeveridge** [comment]
Thanks, @0xMRTT! Do you know of any download badge that I could put next to the Flathub one?

Edit: Also, beside this topic, but do you know if there is even a install badge for aur (arch user repository)?

**Comment by 0xMRTT** [comment]
Go here https://copr.fedorainfracloud.org/coprs/0xmrtt/raider/package/raider and at the bottom, choose between html or markdown badge
