### ISSUE TITLE
Notice thrown re: Gnome 40 and flatpak

### ISSUE THREAD

**Issue by stc4dr** [ADBeveridge/raider#78]
"The GNOME 40 runtime is no longer supported as of March 21, 2022. Please ask your application developer to migrate to a supported platform."
Platform: Ubuntu 20.04
app: File Shredder
version: 1.3.1

**Comment by ADBeveridge** [comment]
Hm, when you install it does it install Gnome SDK 40 or 43? I never had Raider developed for Gnome 40, the first SDK it had was GNOME 42. (the SDK is the runtime)

**Comment by stc4dr** [comment]
Just confirmed it is GNOME 43. My error in opening issue; something on my system is throwing error about GNOME 40 and I initially focused on File Shredder.

**Comment by ADBeveridge** [comment]
No problem. :)
