### ISSUE TITLE
Simplify Preferences Dialog

### ISSUE THREAD

**Issue by ADBeveridge** [ADBeveridge/raider#92]
The preferences dialog as it is is too detailed. Get rid of 
 - Hide Shredding
 - Remove Method
 - Overwrite data source (too niche for real use)
 - Do not round file sizes (not applicable to secure-delete)
Convert number of passes into an option to do fast shredding or secure shredding.

**Comment by ADBeveridge** [comment]
Fixed by f13f9dfda5a92bac68d94c62705811f521c7f4da.

**Comment by benjamin051000** [comment]
What are the defaults now?

**Comment by ADBeveridge** [comment]
The defaults are more or less the same. I realized that nobody was using the preferences dialog when a reviewer didn't even mention it. Although there are double the number of passes from before. Some things haven't been implemented yet, like forcing a shred (in case of insufficient file permissions).
